[package]
name = "advent"
version = "0.1.0"
authors = ["Michael Diamond"]
edition = "2018"

[dependencies]
chrono = "0.4"
itertools = "0.8.0"
lazy_static = "1.2.0"
parameterized_test = "0.1.0"
regex = "1"
typed-arena = "1.4.1"
